### PR TITLE
Move to GitHub actions

### LINKED ISSUE #54: Move away from Travis
Yes, we're still using Travis 😅 

I assume to GitHub Actions since urllib3 and quite a lot of other projects use it.

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
Also include Python 3.9 in CI

Closes #54

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
@sethmlarson I think you'll need to activate GH actions for this to work? It's been a while since I've done this though, so I may have missed something.

**Comment by sethmlarson** [comment]
@yeraydiazdiaz Looks like the action definition isn't valid: https://github.com/sethmlarson/socksio/actions/runs/1746283892

**Comment by yeraydiazdiaz** [comment]
Thanks @sethmlarson, I think everything is working now except for disabling Travis in the project settings.

Btw I noticed you're not using Codecov in urllib, not sure if you want to do the same here, if so we can tackle it separately.

**Comment by sethmlarson** [comment]
Let's do the same and tackle separately! Thanks for this, I'll remove Travis completely.

**Review by sethmlarson — APPROVED** [review]

**Pull request merged**
